In [9]:
import pandas as pd
import os

In [10]:
data_dir = '../data/'

In [11]:
df_bio = pd.read_csv(os.path.join(data_dir, 'GSE61260.tsv'), sep='\t')

df_bio_t = df_bio.set_index('Gene').T
df_bio_t.index.name = 'Sample_ID'
df_bio_t = df_bio_t.reset_index()
df_bio_t.head()

test = df_bio_t.drop(columns = ['Sample_ID'])
test.describe()

Gene,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000283740,ENSG00000283787,ENSG00000283907,ENSG00000283913,ENSG00000284032,ENSG00000284373,ENSG00000284387,ENSG00000284395,ENSG00000284505,ENSG00000284552
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,...,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,10.357705,0.077771,7.190684,3.075064,0.967899,0.801064,52.408068,4.283158,10.111591,3.059486,...,0.348983,-0.098623,2.073094,0.957279,0.433078,-0.080149,0.168239,-0.005561,-0.411707,1.728179
std,2.056698,0.146238,1.653973,0.404083,0.255981,0.271511,6.187410,0.841152,1.810253,0.427101,...,0.202099,0.116810,2.012320,0.407859,0.202175,0.141405,0.258400,0.175642,0.192992,0.576459
min,5.302871,-0.181089,3.108167,1.492620,0.512570,0.142207,37.987642,2.607075,5.354153,2.021877,...,-0.141667,-0.340155,0.080582,-0.150676,0.009329,-0.400835,-0.157818,-0.305665,-0.815156,0.537022
25%,9.142293,-0.023800,6.097516,2.860699,0.769144,0.614453,48.138893,3.728067,8.920728,2.760388,...,0.211649,-0.179073,0.922623,0.673363,0.315794,-0.173418,0.004699,-0.119500,-0.543058,1.308151
50%,10.318095,0.048115,7.198594,3.062987,0.947630,0.755181,52.487952,4.044070,9.981632,3.035390,...,0.338875,-0.111330,1.507144,0.995494,0.412936,-0.079359,0.086307,-0.049108,-0.456372,1.641472
75%,11.519846,0.147821,8.226639,3.339106,1.128930,0.965093,55.872893,4.805941,11.101110,3.365144,...,0.458741,-0.034558,2.407379,1.185835,0.501075,-0.001327,0.270915,0.108971,-0.311328,2.121318
max,23.292853,0.580903,11.633361,4.639541,1.766290,1.605540,72.124643,6.934298,17.172328,4.836872,...,0.923245,0.337941,15.231648,2.165370,1.489534,0.300387,1.756309,0.900492,0.259790,3.264821

In [12]:
df_meta = pd.read_csv(os.path.join(data_dir, 'metadata_GSE61260.tsv'), sep='\t')
df_meta.head()

,refinebio_accession_code,experiment_accession,refinebio_age,refinebio_cell_line,refinebio_compound,refinebio_developmental_stage,refinebio_disease,refinebio_disease_stage,refinebio_genetic_information,refinebio_organism,...,scan_protocol,series_id,source_name_ch1,status,submission_date,supplementary_file,taxid_ch1,title,treatment_protocol_ch1,type
0,GSM1501013,GSE61260,70.0,NaN,NaN,NaN,normal control,NaN,NaN,HOMO_SAPIENS,...,according to the manufacturers protocols,"['GSE61256', 'GSE61260']",liver tissue,Public on Nov 03 2014,Sep 09 2014,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1501...,9606,Human liver expression data from subject S11a1...,not applicable,RNA
1,GSM1501014,GSE61260,49.0,NaN,NaN,NaN,healthy obese,NaN,NaN,HOMO_SAPIENS,...,according to the manufacturers protocols,"['GSE61256', 'GSE61260']",liver tissue,Public on Nov 03 2014,Sep 09 2014,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1501...,9606,Human liver expression data from subject S11a1...,not applicable,RNA
2,GSM1501015,GSE61260,76.0,NaN,NaN,NaN,normal control,NaN,NaN,HOMO_SAPIENS,...,according to the manufacturers protocols,"['GSE61256', 'GSE61260']",liver tissue,Public on Nov 03 2014,Sep 09 2014,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1501...,9606,Human liver expression data from subject S11a1...,not applicable,RNA
3,GSM1501016,GSE61260,48.0,NaN,NaN,NaN,normal control,NaN,NaN,HOMO_SAPIENS,...,according to the manufacturers protocols,"['GSE61256', 'GSE61260']",liver tissue,Public on Nov 03 2014,Sep 09 2014,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1501...,9606,Human liver expression data from subject S11a1...,not applicable,RNA
4,GSM1501017,GSE61260,73.0,NaN,NaN,NaN,normal control,NaN,NaN,HOMO_SAPIENS,...,according to the manufacturers protocols,"['GSE61256', 'GSE61260']",liver tissue,Public on Nov 03 2014,Sep 09 2014,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1501...,9606,Human liver expression data from subject S11a1...,not applicable,RNA

In [13]:
df_combined = pd.merge(df_bio_t, df_meta[['refinebio_accession_code', 'refinebio_disease', 'characteristics_ch1_Sex', 'characteristics_ch1_age', 'characteristics_ch1_bmi']],
                           left_on='Sample_ID', right_on='refinebio_accession_code', how='inner').drop(columns=['refinebio_accession_code'])
df_combined.rename(columns = {"refinebio_disease" : "Disease"}, inplace=True)
df_combined = pd.get_dummies(df_combined, columns=['characteristics_ch1_Sex'], drop_first=True, dtype='int')
df_combined.head()

df_combined['Disease'].value_counts()

Disease
normal control    38
healthy obese     24
nash              23
nafld             23
psc               14
pbc               11
Name: count, dtype: int64

In [17]:

# df_combined = df_combined.drop(columns = ['characteristics_ch1_age', 'characteristics_ch1_Sex_male'])

path = os.path.join(data_dir, 'combined.csv')

# df_combined.to_csv(path, index=False)

df_combined.head(50)

,Sample_ID,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,...,ENSG00000283907,ENSG00000283913,ENSG00000284032,ENSG00000284373,ENSG00000284387,ENSG00000284395,ENSG00000284505,ENSG00000284552,Disease,characteristics_ch1_bmi
0,GSM1501013,8.002176,0.175238,4.949994,3.285351,0.959516,0.672894,59.325067,4.168056,8.104327,...,3.031789,0.903138,1.222211,0.132392,0.491394,-0.079424,-0.255411,3.071849,normal control,27.1
1,GSM1501014,23.292853,-0.031148,5.657237,2.786927,1.203578,0.358625,46.002714,4.889903,7.588060,...,1.819534,-0.021741,0.487849,-0.066907,0.195198,0.178077,-0.190626,1.399320,healthy obese,30.5
2,GSM1501015,10.557890,0.097413,7.680354,2.795125,0.789783,0.733455,43.835288,5.133417,9.559194,...,1.914932,0.424076,0.423539,-0.155705,0.086307,0.230390,-0.489850,1.632879,normal control,25.3
3,GSM1501016,10.272135,0.066298,8.835539,3.166677,0.941032,0.755181,51.390227,4.168056,10.980774,...,1.313128,0.501803,0.357365,-0.321937,0.232894,-0.066718,-0.233382,2.117271,normal control,25.8
4,GSM1501017,8.290414,-0.039647,5.792685,2.203175,0.846344,0.612263,55.423440,3.657327,10.710821,...,4.507792,0.120017,0.452607,-0.263615,0.443599,0.291308,-0.474034,3.032463,normal control,23.5
5,GSM1501018,15.192030,0.081176,6.097516,3.566501,1.045216,0.494167,61.264090,5.202169,12.536387,...,2.189540,0.534677,0.606356,-0.190758,-0.031517,-0.101669,-0.623832,1.560197,pbc,27.8
6,GSM1501019,10.677884,0.148528,4.299517,3.382250,0.549977,0.720861,52.831945,2.984661,7.609664,...,2.945203,0.872271,0.371177,-0.042413,-0.008590,0.158892,-0.567165,3.264821,nash,30.1
7,GSM1501020,10.449758,-0.055885,8.071636,2.992545,1.054343,0.843073,53.954362,4.346267,10.351082,...,1.432103,1.036273,0.422989,-0.110743,-0.054957,-0.113490,-0.744061,1.946250,normal control,23.6
8,GSM1501021,11.319727,-0.086860,8.192868,3.846907,1.078082,0.830211,51.075007,4.833854,10.194470,...,0.917876,1.259424,0.907421,-0.088442,0.031722,-0.104440,-0.374976,2.155264,normal control,23.4
9,GSM1501022,10.533337,0.039903,8.030668,3.177224,0.999544,0.853691,55.423440,3.803235,12.316474,...,0.888948,1.351098,0.850988,0.142686,0.749407,0.243824,0.184332,1.155702,psc,49.2
10,GSM1501023,11.602021,0.108971,8.221472,2.166775,0.662410,1.414691,44.060324,3.784417,11.979067,...,0.423650,1.094217,0.609638,-0.312651,0.694063,0.438508,-0.452439,0.537022,healthy obese,31.9
11,GSM1501024,8.963786,-0.119060,7.374998,2.556188,1.170710,0.666980,72.124643,6.329082,8.881101,...,2.548214,0.535707,0.412936,0.141247,0.699806,0.039188,-0.623832,2.086370,normal control,26.9
12,GSM1501025,11.519846,-0.012023,6.288612,3.352465,1.317667,0.661641,56.340567,6.072393,10.088240,...,3.265647,0.694893,0.315794,-0.128820,0.010086,-0.033304,-0.388753,2.216354,pbc,30.4
13,GSM1501026,11.602021,-0.112117,8.596500,3.838472,1.187376,0.969904,56.774108,4.686551,11.110411,...,1.886421,1.027835,0.426285,-0.011723,-0.126801,-0.145932,-0.508880,2.300358,normal control,20.7
14,GSM1501027,11.349111,-0.006966,6.102373,3.339106,0.762702,0.687040,40.101804,5.523932,9.260195,...,2.571456,0.931747,0.511566,-0.318206,-0.054223,-0.131520,-0.460497,1.998305,normal control,25.6
15,GSM1501028,9.583834,0.035321,5.947736,3.146006,1.621643,0.579807,51.751153,3.735335,11.480345,...,4.755684,1.351948,0.409769,-0.141327,0.000776,-0.092382,-0.197113,2.657256,normal control,26.6
16,GSM1501029,11.147182,-0.000812,8.211573,3.090492,0.764634,1.121058,62.221284,5.993483,10.287212,...,2.715523,0.317927,0.362451,-0.009023,0.038025,0.080515,-0.260677,1.800189,normal control,23.7
17,GSM1501030,11.027092,0.147197,5.700542,3.407749,1.046575,0.439534,56.774108,4.689575,10.573893,...,5.217703,1.075498,0.611120,-0.147165,0.026028,0.108971,-0.554254,2.420378,normal control,26.8
18,GSM1501031,11.000183,-0.026451,8.903934,3.142118,0.672589,0.563425,51.390227,4.556288,12.095980,...,3.631763,0.673363,0.520487,-0.162280,-0.065147,-0.012384,-0.653423,1.641472,normal control,26.9
19,GSM1501032,10.240776,-0.058381,8.840459,2.885369,1.411766,1.074800,53.175730,5.678675,8.570144,...,2.444550,-0.088648,0.157245,-0.212919,-0.099198,0.094222,-0.023489,1.892730,normal control,25.8
20,GSM1501033,11.705233,0.044102,8.643291,3.289467,0.900894,0.623243,53.175730,3.992054,10.669317,...,2.217288,0.597128,0.249409,-0.233382,0.100686,-0.216629,-0.567165,1.099261,psc,27.1
21,GSM1501034,10.710821,-0.037424,8.559789,3.400090,0.861581,0.558622,54.644835,3.989746,11.948344,...,2.268597,1.029229,0.804201,-0.169142,0.302400,0.056635,-0.489850,1.937311,healthy obese,30.1
22,GSM1501035,9.083462,0.580903,8.039775,2.922123,1.766290,0.833256,61.264090,3.728067,9.686408,...,1.495804,1.115254,0.712794,0.036155,0.270915,-0.059086,-0.412446,2.482077,normal control,26.0
23,GSM1501036,12.427566,0.120504,8.632804,3.712700,1.293175,0.334690,67.376169,4.451191,11.358613,...,1.751182,0.315705,0.514578,-0.069959,-0.051781,-0.111044,-0.815156,1.948721,pbc,29.8
24,GSM1501037,10.880659,0.018536,7.659974,3.060023,0.961888,0.885864,56.774108,4.206359,9.686408,...,1.786613,0.417844,0.496970,-0.232938,0.073039,-0.102075,-0.516258,2.578872,pbc,36.2
25,GSM1501038,5.302871,-0.181089,5.836565,2.971404,0.850803,0.412503,53.553674,3.376221,11.101110,...,7.308654,1.080013,0.331377,-0.229475,0.039844,0.080649,-0.423006,1.968216,normal control,19.1
26,GSM1501039,11.756689,-0.044531,7.386545,3.464364,0.798374,0.415680,47.550262,4.405158,12.941807,...,2.558988,0.393183,0.455584,-0.206945,-0.068491,0.152282,-0.524311,2.146258,pbc,25.4
27,GSM1501040,10.834779,0.198529,8.058561,3.016960,1.115025,0.919749,48.742099,5.720934,7.847802,...,1.828012,0.362451,0.490175,-0.148239,-0.026818,-0.022815,-0.452439,2.258637,normal control,26.0
28,GSM1501041,8.835539,-0.069448,3.409466,3.598801,1.051317,0.965093,52.831945,3.514836,9.285816,...,15.231648,1.220904,0.040839,-0.242082,0.004699,-0.181454,-0.543058,2.444550,normal control,24.9
29,GSM1501042,5.700542,0.577573,7.020929,3.091942,0.924537,0.713128,59.784069,5.011730,7.451089,...,1.383503,1.116451,0.360536,-0.055944,0.036990,-0.139298,-0.341155,1.866817,healthy obese,36.1
30,GSM1501043,12.144994,0.083035,5.544576,3.160684,0.806234,0.449421,49.338394,3.616856,8.920728,...,2.911138,1.568338,0.360729,-0.102919,0.243187,0.186061,-0.289509,1.468771,healthy obese,36.3
31,GSM1501044,12.536387,0.035386,7.129198,2.988991,1.188693,0.515326,58.847412,3.824782,12.970443,...,2.875957,0.816018,0.362548,-0.285761,0.048524,-0.145496,-0.582404,1.951177,pbc,25.4
32,GSM1501045,10.095637,0.131714,5.920884,2.781852,1.149917,0.498457,50.508761,4.585346,10.433296,...,1.341641,1.153684,0.442913,0.038734,0.410206,0.015871,-0.366031,1.753761,normal control,26.4
33,GSM1501046,9.142293,-0.111188,8.460233,3.004650,0.900701,0.401784,48.138893,4.017252,9.852065,...,1.815058,0.872271,0.638374,-0.133600,0.239028,0.143785,-0.653423,2.345293,normal control,20.1
34,GSM1501047,10.424990,0.003931,6.222320,3.242876,0.947842,0.783547,46.002714,3.762653,9.320897,...,1.808202,1.059665,0.263808,-0.079623,0.392279,-0.075829,-0.469307,1.564097,normal control,29.4
35,GSM1501048,12.144994,0.139282,9.055234,3.062987,1.101663,0.620310,61.264090,5.661652,12.742193,...,1.696349,0.636251,0.425584,-0.138957,-0.031207,-0.135146,-0.479012,1.358676,pbc,23.9
36,GSM1501049,8.638089,0.096796,6.216929,2.776061,0.860366,0.662571,50.794934,3.917049,13.891322,...,5.128351,0.504050,0.414817,-0.197821,0.263887,0.105108,-0.508880,1.551984,normal control,25.3
37,GSM1501050,12.757457,0.008129,6.600616,3.115662,0.721847,0.720517,50.209501,3.878616,11.900492,...,2.407379,1.135248,0.396240,-0.021241,0.047854,-0.085085,-0.524311,1.557855,normal control,22.2
38,GSM1501051,12.588852,0.063724,8.145385,3.351635,0.912747,0.917456,46.002714,3.817587,10.889261,...,1.945381,0.437951,0.269786,-0.360586,-0.096206,-0.152606,-0.116171,1.060372,pbc,23.2
39,GSM1501052,11.379152,-0.082878,5.028855,3.539647,0.733285,0.703525,51.075007,3.044091,10.126374,...,2.256664,0.811841,0.467104,0.227496,0.307850,0.040581,0.054416,1.837228,healthy obese,46.6
40,GSM1501053,7.672562,0.105315,6.801276,1.492620,0.699964,1.294255,45.542441,3.563527,13.080841,...,8.054494,0.804398,0.255772,-0.012262,1.756309,-0.074159,-0.474034,1.533139,nash,54.8
41,GSM1501054,10.272135,0.089331,10.140574,2.721694,0.682004,0.917456,53.954362,3.814485,14.053774,...,1.225684,0.974941,0.257710,-0.309386,0.057545,-0.040323,-0.600882,2.748849,healthy obese,55.6
42,GSM1501055,13.620867,-0.038101,9.060454,2.923411,0.609076,0.866106,47.848576,5.402717,9.334472,...,1.055732,1.553939,0.588490,-0.007403,0.414181,-0.260039,-0.567165,1.617031,nafld,36.9
43,GSM1501056,8.580946,0.007565,6.713312,2.882645,1.201512,0.608230,53.553674,4.185161,10.095637,...,1.296191,1.141912,0.204826,0.147686,0.022964,-0.100909,-0.388753,2.284987,healthy obese,49.6
44,GSM1501057,9.823778,0.073431,6.742209,2.788164,1.064843,0.802864,54.302661,3.867019,9.746510,...,2.047091,1.072641,0.565295,-0.173418,0.032670,0.045955,-0.653423,2.922123,healthy obese,40.4
45,GSM1501058,10.400223,0.392279,10.907418,2.956575,1.482881,0.737421,49.900526,4.231691,12.012622,...,1.408439,1.071192,0.462914,0.018970,0.061795,-0.078008,-0.460497,1.858316,nafld,47.4
46,GSM1501059,11.119439,0.135744,7.572203,3.286180,1.086332,0.809033,59.325067,3.848946,10.367479,...,1.466027,1.050393,0.642570,0.005442,-0.087788,0.170431,-0.533174,2.121318,healthy obese,48.0
47,GSM1501060,10.818020,0.210095,7.725255,2.951076,0.841171,0.921382,59.784069,3.252587,11.261768,...,1.989389,1.179391,0.284455,0.184828,0.011050,0.166611,-0.495767,1.055041,nafld,43.5
48,GSM1501061,13.135974,0.067216,6.901618,2.644468,0.669297,1.060372,48.431973,4.527819,10.249269,...,1.043619,0.365049,0.281323,-0.005779,0.131434,0.055347,-0.029479,1.383790,pbc,34.9
49,GSM1501062,10.790704,-0.013376,8.559789,2.491371,0.680232,1.060372,46.964546,3.663056,12.536387,...,1.175305,1.029229,0.594728,0.003350,0.622806,-0.047737,-0.278390,2.147193,nash,41.8